pipeline { 
    agent any 

    tools {
        nodejs 'node-12.18.3'
    }

    options {
        timeout(time: 2, unit: 'MINUTES')
    }

    stages { 
        stage('Install Dependencies') {  
            steps { 
                sh 'npm i'
            } 
        }
        stage('Stop the server') {  
            steps { 
                sh 'pm2 delete api'  
            } 
        } 
        stage('Deploy the server') {  
            steps { 
                sh 'pm2 start ecosystem.config.js --env development'  
            } 
        } 
    } 
}